export const productosRehabilitacion = {
  cementados: {
    id: "cementados",
    nombre: "Cementados",
    tiposRehabilitacion: [
      "Corona",
      "Inlay",
      "Onlay",
      "Maryland",
      "Cofia",
      "Puente Anatómico",
    ],
    casos: [
      {
        tipo: "Corona",
        materialId: "resina3d",
        precio: 39900,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["A3"],
      },
      {
        tipo: "Onlay",
        materialId: "resina3d",
        precio: 46669,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["A3"],
      },
      {
        tipo: "Onlay",
        materialId: "disilicato",
        precio: 65900,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["A1", "A2", "B1", "B2", "BL"],
      },
      {
        tipo: "Inlay",
        materialId: "resina3d",
        precio: 46669,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["A3"],
      },
      {
        tipo: "Inlay",
        materialId: "disilicato",
        precio: 65900,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["A1", "A2", "B1", "B2", "BL"],
      },
      {
        tipo: "Cofia",
        materialId: "zirconio_shtc",
        precio: 17000,
        despachoDias: 5,
        colores: ["A1", "A2", "A3.5", "A4", "B1", "B2", "B3", "B4", "C1", "C2", "C3", "C4", "D2", "D3", "D4"],
      },
      {
        tipo: "Fresado de Conexión unitaria",
        materialId: "zirconio_shtc",
        precio: 19319,
        despachoDias: 1,
        categoria: "CENTRO DE FRESADO",
        subcategoria: "ZIRCONIO",
        sku: "1.2.2.4",
        nombreProducto: "Fresado de Conexión unitaria de Zirconio SHTC",
      },
      {
        tipo: "Corona",
        materialId: "zirconio_shtc",
        precio: 64990,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["A1", "A2", "A3.5", "A4", "B1", "B2", "B3", "B4", "C1", "C2", "C3", "C4", "D2", "D3", "D4"],
        categoria: "CENTRO DE FRESADO",
        subcategoria: "ZIRCONIO",
        sku: "1.2.3.7",
        nombreProducto: "Carilla, Corona o incrustación de Zirconio SHTC",
      },
      {
        tipo: "Maryland",
        materialId: "zirconio_shtc",
        precio: 52000,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["BL", "A1", "A2", "A3", "B1", "D3", "C1", "C2", "C4", "D2"],
        categoria: "CENTRO DE FRESADO",
        subcategoria: "ZIRCONIO",
        sku: "1.2.2.5",
        nombreProducto: "Fresado de Puente Maryland de Zirconio SHTC",
      },
      {
        tipo: "Corona",
        materialId: "zirconio_3dpro_multilayer",
        precio: 71500,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["BL", "A1", "A2", "A3", "B1", "D3", "C1", "C2", "C4", "D2"],
        categoria: "CENTRO DE FRESADO",
        subcategoria: "ZIRCONIO",
        sku: "1.2.3.8.0",
        nombreProducto: "Carilla, Corona o incrustación de Zirconio 3D PRO Multilayer",
      },
      {
        tipo: "Puente Anatómico",
        materialId: "zirconio_shtc",
        precio: 74990,
        precioPontico: 52920,
        despachoDias: 5,
        colores: ["BL", "A1", "A2", "A3", "B1", "D3", "C1", "C2", "C4", "D2"],
        requierePuente: true,
      },
      {
        tipo: "Puente Anatómico",
        materialId: "zirconio_3dpro_multilayer",
        precio: 74990,
        precioPontico: 52920,
        despachoDias: 5,
        colores: ["BL", "A1", "A2", "A3", "B1", "D3", "C1", "C2", "C4", "D2"],
        requierePuente: true,
      },
      {
        tipo: "Conexión unitaria",
        materialId: "zirconio_3dpro_multilayer",
        precio: 21000,
        despachoDias: 1,
        categoria: "CENTRO DE FRESADO",
        subcategoria: "ZIRCONIO",
        sku: "1.2.3.4",
        nombreProducto: "Conexión unitaria de Zirconio 3D Pro Multilayer",
      },
      {
        tipo: "Maryland",
        materialId: "zirconio_3dpro_multilayer",
        precio: 52000,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["BL", "A1", "A2", "A3", "B1", "D3", "C1", "C2", "C4", "D2"],
        categoria: "CENTRO DE FRESADO",
        subcategoria: "ZIRCONIO",
        sku: "1.2.3.5",
        nombreProducto: "Puente Maryland de Zirconio 3D Pro Multilayer",
      },

      {
        tipo: "Cofia",
        materialId: "zirconio_blanco",
        precio: 14286,
        despachoDias: 1,
        categoria: "CENTRO DE FRESADO",
        subcategoria: "ZIRCONIO",
        sku: "1.2.4.0",
        nombreProducto: "Cofia, Casquete, Corona o Estructura múltiple de Zirconio Blanco",
      },
    ],
    // subtipos: ["Terminación", "Sin terminación"],
    materiales: [
      { id: "resina3d", nombre: "Resina 3D" },
      { id: "zirconio_shtc", nombre: "Zirconio SHTC" },
      { id: "zirconio_3dpro_multilayer", nombre: "Zirconio 3D PRO Multilayer" },
      { id: "zirconio_blanco", nombre: "Zirconio Blanco" },
      {
        id: "disilicato",
        nombre: "Disilicato",
        subOpciones: [
          {
            id: "marca_receta",
            nombre: "Marca (Receta)",
            requiereReceta: true,
            etiquetaReceta: "Informacion de aditamiennto (marca, tipo, etc.)",
          },
        ],
      },
    ],
  },
  atornillados: {
    id: "atornillados",
    nombre: "Atornillados",
    casos: [
      {
        tipo: "Corona sobre implante",
        coronaId: "zirconio",
        precio: 72500,
        despachoDias: 5,
        colores: ["BL", "A1", "A2", "A3", "B1", "D3", "C1", "C2", "C4", "D2"],
      },
      {
        tipo: "Corona sobre implante",
        coronaId: "resina3d",
        precio: 39900,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["A3"],
      },
      {
        tipo: "Corona cemento atornillada",
        coronaId: "disilicato",
        precio: 79990,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["A1", "B1", "B2", "BL"],
      },
      {
        tipo: "Corona sobre implante",
        coronaId: "disilicato",
        precio: 79990,
        despachoDias: 5,
        precioByPieza: true,
        colores: ["A1", "B1", "B2", "BL"],
      },
      {
        tipo: "Pilar personalizado sobre implante",
        pilarId: "pilar_personalizado",
        material: "CrCo Sinterizado",
        precio: 22900,
        despachoDias: 5,
        adicionalTornillos: 7500,
      },
    ],
    tiposRehabilitacion: [
      "Corona sobre implante",
      "Corona cemento atornillada",
      "Pilar personalizado sobre implante",
    ],
    requiereSeleccionTresComponentes: true,
    componentes: {
      pilar: {
        id: "pilar",
        etiqueta: "Pilar",
        opciones: [
          {
            id: "pilar_tbase_externo",
            nombre: "Pilar Tbase externo",
          },
          {
            id: "tbase_dit",
            nombre: "Tbase DIT",
          },
          {
            id: "pilar_personalizado",
            nombre: "Pilar Personalizado",
          },
        ],
      },
      corona: {
        id: "corona",
        etiqueta: "Corona",
        opciones: [
          { id: "resina3d", nombre: "Resina 3D" },
          { id: "disilicato", nombre: "Disilicato" },
          { id: "zirconio", nombre: "Zirconio" },
          // {
          //   id: "premill",
          //   nombre: "Premill",
          //   permiteSeleccionCeramica: true,
          //   opcionesCeramica: ["Cerámica adicional"],
          // },
          {
            id: "laser_metal",
            nombre: "Laser Metal",
            incluyeCeramica: true,
            opcionesCeramica: ["Cerámica"],
          },
        ],
      },
      tornillo: {
        id: "tornillo",
        etiqueta: "Tornillo",
        opciones: ["Externo", "DIT"],
      },
    },
  },
};

export const REHAB_CONFIG = productosRehabilitacion;
